#!/usr/bin/python3
"""
A quick script to run fibserv from within the repository. From the
root of the repo, simply run './deploy/run' and off you go!
"""

import os.path
from pprint import pprint
from sys import path as PATH

PATH.append(os.path.abspath(os.path.curdir))

from fibserv.api import main

main()
